### ISSUE TITLE
Several "Updates" go to the same wrong page

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit.org#107]
In https://urbit.org/posts/updates/, `~2018.12.18 Update`, `~2018.11.20 Update`, `~2018.10.24 Update`, and `~2018.10.12 Update` all link to the [same wrong post](https://urbit.org/posts/update/) from 2017.

It looks like the content does not exist on urbit.org at all. I found results for posts I wrote as [Google results](https://www.google.com/search?q=%2260+degree+weather%22+site%3Aurbit.org&oq=%2260+degree+weather%22+site%3Aurbit.org&aqs=chrome..69i57.2237j0j7&sourceid=chrome&ie=UTF-8), but those get a 404.

**Comment by flowerornament** [comment]
This appears to be caused by there not being a space between the front-matter and the content. I think this was a mistake on @friederjanmoerman's part, which I've been correcting slowly as I come across documents, but might require a concerted effort.

Documents should be formatted as such:

```
+++
front = "matter"
+++

Content ...
````

**Comment by flowerornament** [comment]
Fixed in https://github.com/urbit/urbit.org/commit/7292d01ac58603c9d7317b851a2a1451688be18c

**Comment by rmariani** [comment]
I just checked links on the live site again, and is not fixed

**Comment by flowerornament** [comment]
@rmariani thanks, will check on this soon

**Comment by matildepark** [comment]
In my RSS investigations I found an easy way to see them all. Ctrl+F `<guid>https://urbit.org/posts/update/</guid>` in a feed validator:

https://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Furbit.org%2Frss.xml

As to why, I peeked a bit and have no immediate idea.

**Comment by flowerornament** [comment]
@matildepark I figured it out – when there's a valid date in the filename, it gets stripped out, so all files with names like `2017-11-14-update.md` are rendered as `update.html`. Files with names like `2017-1-14-update.md` are rendered as `2017-1-14-update.md` because `2017-1-14` is not a valid date in Zola world, and as such it isn't stripped.

I'm not sure there's a way around this other than to rename all of the posts.

Logged an issue at https://github.com/getzola/zola/issues/770

**Comment by flowerornament** [comment]
Pushed an example fix: https://github.com/urbit/urbit.org/blob/master/content/posts/2017-12-22-update.md

Just need to add the "slug" metadata to all posts with dates the contain double-digit months and days.

@matildepark or @francescanarea  – either of you want to tackle this?
